{% set name = "uiautomation" %}
{% set version = "2.0.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uiautomation-{{ version }}.tar.gz
  sha256: 729e36f8f3e38ca493686acb0fbf429de2d4a639fc2e8de226315fb1e455c5b9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - comtypes >=1.2.1
    - setuptools
  run:
    - python >={{ python_min }}
    - typing
    - comtypes >=1.2.1
    - __win

test:
  imports:
    - uiautomation
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/yinkaisheng/Python-UIAutomation-for-Windows
  summary: Python UIAutomation for Windows
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
