{% set name = "uiautomation" %}
{% set version = "2.0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uiautomation-{{ version }}.tar.gz
  sha256: 1e891d7a1d3e913e25b3cfed9d03f0a4f91ed2e80b827d9ea85141a679ef9ada

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - comtypes >=1.1.10
  run:
    - python >={{ python_min }}
    - typing
    - comtypes >=1.1.10
    - __win

test:
  requires:
    - python {{ python_min }}
  imports:
    - uiautomation

about:
  home: https://github.com/yinkaisheng/Python-UIAutomation-for-Windows
  summary: Python UIAutomation for Windows
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
